"""Manual-registry adapter — curated PCR/PEFCR entries for programs whose
listings are JS-gated or behind portals (EU PEFCR, IBU, INIES later).
These are verified direct-download URLs (HTTP 200, application/pdf). Expand by
appending entries; this is the honest "known universe" seed for these operators.
"""

ENTRIES = [
    # ── PEFCR Guidance (method doc) ──
    {"operator_id": "eu-ef", "pcr_number": "PEFCR-Guidance-6.3", "pcr_type": "pefcr",
     "title": "PEFCR Guidance document v6.3 (EU Environmental Footprint Category Rules guidance)",
     "version_label": "6.3", "valid_until": None, "cpc_code": None, "language": "en", "method_family": "PEF",
     "pdf_url": "https://eplca.jrc.ec.europa.eu/permalink/PEFCR_guidance_v6.3-2.pdf",
     "detail_url": "https://eplca.jrc.ec.europa.eu/EnvironmentalFootprint.html"},
    # ── IBU Part A — metadata-only (portal JS-gated); EPD-vs-PCR disambiguation marker ──
    {"operator_id": "ibu", "pcr_number": "IBU-PartA-TODO", "pcr_type": "pcr",
     "title": "IBU PCR Part A (general programme rules) — URL TODO (portal is JS-gated)",
     "version_label": None, "valid_until": None, "cpc_code": None, "language": "de", "method_family": "EN15804",
     "pdf_url": None, "detail_url": "https://www.ibu-epd.com/en/published-epds/"},
    # ── Adopted EU PEFCRs + US PCRs — all verified %PDF, HTTP 200, 2026-06-18 ──
    {"operator_id": "eu-ef", "pcr_number": "Decorative Paints v1.0", "pcr_type": "pefcr",
     "title": "PEFCR Decorative Paints v1.0", "version_label": None, "valid_until": None, "cpc_code": None,
     "language": "en", "method_family": "PEF", "pdf_url": "https://www.sazp.sk/dokument/f/dekorativne_farby.pdf",
     "detail_url": "https://www.sazp.sk/dokument/f/dekorativne_farby.pdf"},
    {"operator_id": "eu-ef", "pcr_number": "Thermal Insulation", "pcr_type": "pefcr",
     "title": "PEFCR Thermal Insulation", "version_label": None, "valid_until": None, "cpc_code": None,
     "language": "en", "method_family": "PEF", "pdf_url": "https://www.sazp.sk/dokument/f/tepelna-izolacia.pdf",
     "detail_url": "https://www.sazp.sk/dokument/f/tepelna-izolacia.pdf"},
    {"operator_id": "eu-ef", "pcr_number": "Dairy Products (final update)", "pcr_type": "pefcr",
     "title": "PEFCR Dairy Products (final update)", "version_label": None, "valid_until": None, "cpc_code": None,
     "language": "en", "method_family": "PEF", "pdf_url": "https://eda.euromilk.org/wp-content/uploads/2025/02/PEFCR-DairyProducts_update_final.pdf",
     "detail_url": "https://eda.euromilk.org/wp-content/uploads/2025/02/PEFCR-DairyProducts_update_final.pdf"},
    {"operator_id": "eu-ef", "pcr_number": "Feed for food-producing animals", "pcr_type": "pefcr",
     "title": "PEFCR Feed for food-producing animals", "version_label": None, "valid_until": None, "cpc_code": None,
     "language": "en", "method_family": "PEF", "pdf_url": "https://fefac.eu/wp-content/uploads/2025/02/PEFCR_Feed_FinalPEFCRs-update-10-02-2025.pdf",
     "detail_url": "https://fefac.eu/wp-content/uploads/2025/02/PEFCR_Feed_FinalPEFCRs-update-10-02-2025.pdf"},
    {"operator_id": "eu-ef", "pcr_number": "Beer", "pcr_type": "pefcr",
     "title": "PEFCR Beer", "version_label": None, "valid_until": None, "cpc_code": None,
     "language": "en", "method_family": "PEF", "pdf_url": "https://www.sazp.sk/dokument/f/pivo.pdf",
     "detail_url": "https://www.sazp.sk/dokument/f/pivo.pdf"},
    {"operator_id": "eu-ef", "pcr_number": "Wine", "pcr_type": "pefcr",
     "title": "PEFCR Wine", "version_label": None, "valid_until": None, "cpc_code": None,
     "language": "en", "method_family": "PEF", "pdf_url": "https://www.sazp.sk/dokument/f/vino.pdf",
     "detail_url": "https://www.sazp.sk/dokument/f/vino.pdf"},
    {"operator_id": "eu-ef", "pcr_number": "Pasta", "pcr_type": "pefcr",
     "title": "PEFCR Pasta", "version_label": None, "valid_until": None, "cpc_code": None,
     "language": "en", "method_family": "PEF", "pdf_url": "https://www.sazp.sk/dokument/f/cestoviny.pdf",
     "detail_url": "https://www.sazp.sk/dokument/f/cestoviny.pdf"},
    {"operator_id": "eu-ef", "pcr_number": "Packed Water", "pcr_type": "pefcr",
     "title": "PEFCR Packed Water", "version_label": None, "valid_until": None, "cpc_code": None,
     "language": "en", "method_family": "PEF", "pdf_url": "https://www.sazp.sk/dokument/f/balena_voda.pdf",
     "detail_url": "https://www.sazp.sk/dokument/f/balena_voda.pdf"},
    {"operator_id": "eu-ef", "pcr_number": "Marine Fish", "pcr_type": "pefcr",
     "title": "PEFCR Marine Fish", "version_label": None, "valid_until": None, "cpc_code": None,
     "language": "en", "method_family": "PEF", "pdf_url": "https://www.marinefishpefcr.eu/_files/ugd/2c010a_b71ec7a94c6346b18214b608eb3c24d2.pdf",
     "detail_url": "https://www.marinefishpefcr.eu/_files/ugd/2c010a_b71ec7a94c6346b18214b608eb3c24d2.pdf"},
    {"operator_id": "eu-ef", "pcr_number": "Leather", "pcr_type": "pefcr",
     "title": "PEFCR Leather", "version_label": None, "valid_until": None, "cpc_code": None,
     "language": "en", "method_family": "PEF", "pdf_url": "https://www.sazp.sk/dokument/f/koza.pdf",
     "detail_url": "https://www.sazp.sk/dokument/f/koza.pdf"},
    {"operator_id": "eu-ef", "pcr_number": "Batteries & Accumulators", "pcr_type": "pefcr",
     "title": "PEFCR Batteries & Accumulators", "version_label": None, "valid_until": None, "cpc_code": None,
     "language": "en", "method_family": "PEF", "pdf_url": "https://www.sazp.sk/dokument/f/baterie-a-akumulatory-pdf.pdf",
     "detail_url": "https://www.sazp.sk/dokument/f/baterie-a-akumulatory-pdf.pdf"},
    {"operator_id": "eu-ef", "pcr_number": "Hot & Cold Water Pipes", "pcr_type": "pefcr",
     "title": "PEFCR Hot & Cold Water Pipes", "version_label": None, "valid_until": None, "cpc_code": None,
     "language": "en", "method_family": "PEF", "pdf_url": "https://www.sazp.sk/dokument/f/potrubie-pre-dodavku-teplej-a-studenej-vody.pdf",
     "detail_url": "https://www.sazp.sk/dokument/f/potrubie-pre-dodavku-teplej-a-studenej-vody.pdf"},
    {"operator_id": "eu-ef", "pcr_number": "Household Heavy Duty Liquid Detergents", "pcr_type": "pefcr",
     "title": "PEFCR Household Heavy Duty Liquid Detergents", "version_label": None, "valid_until": None, "cpc_code": None,
     "language": "en", "method_family": "PEF", "pdf_url": "https://www.sazp.sk/dokument/f/detergenty-do-domacnosti.pdf",
     "detail_url": "https://www.sazp.sk/dokument/f/detergenty-do-domacnosti.pdf"},
    {"operator_id": "eu-ef", "pcr_number": "Intermediate Paper Products", "pcr_type": "pefcr",
     "title": "PEFCR Intermediate Paper Products", "version_label": None, "valid_until": None, "cpc_code": None,
     "language": "en", "method_family": "PEF", "pdf_url": "https://www.sazp.sk/dokument/f/medziprodukty-z-papiera.pdf",
     "detail_url": "https://www.sazp.sk/dokument/f/medziprodukty-z-papiera.pdf"},
    {"operator_id": "eu-ef", "pcr_number": "Metal Sheets", "pcr_type": "pefcr",
     "title": "PEFCR Metal Sheets", "version_label": None, "valid_until": None, "cpc_code": None,
     "language": "en", "method_family": "PEF", "pdf_url": "https://www.sazp.sk/dokument/f/kovove-plechy.pdf",
     "detail_url": "https://www.sazp.sk/dokument/f/kovove-plechy.pdf"},
    {"operator_id": "eu-ef", "pcr_number": "Photovoltaic Electricity", "pcr_type": "pefcr",
     "title": "PEFCR Photovoltaic Electricity", "version_label": None, "valid_until": None, "cpc_code": None,
     "language": "en", "method_family": "PEF", "pdf_url": "https://www.sazp.sk/dokument/f/vyroba-elektrickej-energie-pomocou-fotovoltaickych-zariadeni.pdf",
     "detail_url": "https://www.sazp.sk/dokument/f/vyroba-elektrickej-energie-pomocou-fotovoltaickych-zariadeni.pdf"},
    {"operator_id": "eu-ef", "pcr_number": "Uninterruptible Power Supply (UPS)", "pcr_type": "pefcr",
     "title": "PEFCR Uninterruptible Power Supply (UPS)", "version_label": None, "valid_until": None, "cpc_code": None,
     "language": "en", "method_family": "PEF", "pdf_url": "https://www.sazp.sk/dokument/f/ups-plynule-dodavky-energie.pdf",
     "detail_url": "https://www.sazp.sk/dokument/f/ups-plynule-dodavky-energie.pdf"},
    {"operator_id": "eu-ef", "pcr_number": "T-shirts", "pcr_type": "pefcr",
     "title": "PEFCR T-shirts", "version_label": None, "valid_until": None, "cpc_code": None,
     "language": "en", "method_family": "PEF", "pdf_url": "https://www.sazp.sk/dokument/f/tricka.pdf",
     "detail_url": "https://www.sazp.sk/dokument/f/tricka.pdf"},
    {"operator_id": "eu-ef", "pcr_number": "Pet Food (cats & dogs)", "pcr_type": "pefcr",
     "title": "PEFCR Pet Food (cats & dogs)", "version_label": None, "valid_until": None, "cpc_code": None,
     "language": "en", "method_family": "PEF", "pdf_url": "https://www.sazp.sk/dokument/f/krmivo_pre_psy_a_macky.pdf",
     "detail_url": "https://www.sazp.sk/dokument/f/krmivo_pre_psy_a_macky.pdf"},
    {"operator_id": "eu-ef", "pcr_number": "Cut Flowers & Potted Plants", "pcr_type": "pefcr",
     "title": "PEFCR Cut Flowers & Potted Plants", "version_label": None, "valid_until": None, "cpc_code": None,
     "language": "en", "method_family": "PEF", "pdf_url": "https://www.sazp.sk/dokument/f/rezane-kvety-a-crepnikove-rastliny.pdf",
     "detail_url": "https://www.sazp.sk/dokument/f/rezane-kvety-a-crepnikove-rastliny.pdf"},
    {"operator_id": "us-epd", "pcr_number": "NSF Concrete v2.1", "pcr_type": "pcr",
     "title": "NSF PCR Concrete v2.1", "version_label": None, "valid_until": None, "cpc_code": None,
     "language": "en", "method_family": "EN15804", "pdf_url": "https://d2evkimvhatqav.cloudfront.net/documents/pcr_concrete.pdf",
     "detail_url": "https://d2evkimvhatqav.cloudfront.net/documents/pcr_concrete.pdf"},
    {"operator_id": "us-epd", "pcr_number": "PCA Portland Cement 2020 v3.2", "pcr_type": "pcr",
     "title": "PCA PCR Portland Cement 2020 v3.2", "version_label": None, "valid_until": None, "cpc_code": None,
     "language": "en", "method_family": "EN15804", "pdf_url": "https://www.cement.org/wp-content/uploads/2024/07/pcr-portland-cement-2020-v3-2.pdf",
     "detail_url": "https://www.cement.org/wp-content/uploads/2024/07/pcr-portland-cement-2020-v3-2.pdf"},
    {"operator_id": "us-epd", "pcr_number": "NSF-1112-26 Concrete PCR", "pcr_type": "pcr",
     "title": "NSF-1112-26 Concrete PCR", "version_label": None, "valid_until": None, "cpc_code": None,
     "language": "en", "method_family": "EN15804", "pdf_url": "https://d2evkimvhatqav.cloudfront.net/documents/PCR-Product-Category-Rules/NSF-1112-26.pdf",
     "detail_url": "https://d2evkimvhatqav.cloudfront.net/documents/PCR-Product-Category-Rules/NSF-1112-26.pdf"},
    {"operator_id": "us-epd", "pcr_number": "NSF-1129-26 Concrete Admixtures PCR", "pcr_type": "pcr",
     "title": "NSF-1129-26 Concrete Admixtures PCR", "version_label": None, "valid_until": None, "cpc_code": None,
     "language": "en", "method_family": "EN15804", "pdf_url": "https://d2evkimvhatqav.cloudfront.net/documents/PCR-Product-Category-Rules/NSF-1129-26.pdf",
     "detail_url": "https://d2evkimvhatqav.cloudfront.net/documents/PCR-Product-Category-Rules/NSF-1129-26.pdf"},
    {"operator_id": "us-epd", "pcr_number": "NSF-1112-25 Concrete Extension", "pcr_type": "pcr",
     "title": "NSF-1112-25 Concrete PCR Extension", "version_label": None, "valid_until": None, "cpc_code": None,
     "language": "en", "method_family": "EN15804", "pdf_url": "https://d2evkimvhatqav.cloudfront.net/documents/PCR-Product-Category-Rules/NSF-1112-25Ext.pdf",
     "detail_url": "https://d2evkimvhatqav.cloudfront.net/documents/PCR-Product-Category-Rules/NSF-1112-25Ext.pdf"},
    {"operator_id": "us-epd", "pcr_number": "NSF Gypsum Panel Products 2019 v1.1", "pcr_type": "pcr",
     "title": "NSF Gypsum Panel Products PCR 2019 v1.1", "version_label": None, "valid_until": None, "cpc_code": None,
     "language": "en", "method_family": "EN15804", "pdf_url": "https://d2evkimvhatqav.cloudfront.net/documents/pcr_gypsum_panel_products_2019_1.1.pdf",
     "detail_url": "https://d2evkimvhatqav.cloudfront.net/documents/pcr_gypsum_panel_products_2019_1.1.pdf"},
    {"operator_id": "us-epd", "pcr_number": "NSF-1102-23 Fenestration Assemblies PCR", "pcr_type": "pcr",
     "title": "NSF-1102-23 Fenestration Assemblies PCR", "version_label": None, "valid_until": None, "cpc_code": None,
     "language": "en", "method_family": "EN15804", "pdf_url": "https://d2evkimvhatqav.cloudfront.net/documents/PCR-Product-Category-Rules/fenestration-assemblies-nsf-1102-23.pdf",
     "detail_url": "https://d2evkimvhatqav.cloudfront.net/documents/PCR-Product-Category-Rules/fenestration-assemblies-nsf-1102-23.pdf"},
    {"operator_id": "us-epd", "pcr_number": "GANA Flat Glass PCR", "pcr_type": "pcr",
     "title": "GANA Flat Glass PCR", "version_label": None, "valid_until": None, "cpc_code": None,
     "language": "en", "method_family": "EN15804", "pdf_url": "https://d2evkimvhatqav.cloudfront.net/documents/GANA_Flat_Glass_PCR.pdf",
     "detail_url": "https://d2evkimvhatqav.cloudfront.net/documents/GANA_Flat_Glass_PCR.pdf"},
    {"operator_id": "us-epd", "pcr_number": "BIFMA Seating PCR", "pcr_type": "pcr",
     "title": "BIFMA Seating PCR", "version_label": None, "valid_until": None, "cpc_code": None,
     "language": "en", "method_family": "EN15804", "pdf_url": "https://d2evkimvhatqav.cloudfront.net/documents/seating_pcr-new.pdf",
     "detail_url": "https://d2evkimvhatqav.cloudfront.net/documents/seating_pcr-new.pdf"},
    {"operator_id": "us-epd", "pcr_number": "ICC-ES PCR-1002 Plastic Pipe & Fittings", "pcr_type": "pcr",
     "title": "ICC-ES PCR-1002 Plastic Pipe & Fittings", "version_label": None, "valid_until": None, "cpc_code": None,
     "language": "en", "method_family": "EN15804", "pdf_url": "https://icc-es.org/wp-content/uploads/acceptance-criteria/PCR-1002.pdf",
     "detail_url": "https://icc-es.org/wp-content/uploads/acceptance-criteria/PCR-1002.pdf"},
    {"operator_id": "us-epd", "pcr_number": "SCS Addendum Construction Products", "pcr_type": "pcr",
     "title": "SCS PCR Addendum Construction Products", "version_label": None, "valid_until": None, "cpc_code": None,
     "language": "en", "method_family": "EN15804", "pdf_url": "https://cdn.scsglobalservices.com/files/program_documents/scs_pcr_addendum_constructionproducts_v1-0_092717.pdf",
     "detail_url": "https://cdn.scsglobalservices.com/files/program_documents/scs_pcr_addendum_constructionproducts_v1-0_092717.pdf"},
    {"operator_id": "us-epd", "pcr_number": "Circular Ecology Construction & Building v1.0", "pcr_type": "pcr",
     "title": "Circular Ecology PCR Construction & Building v1.0", "version_label": None, "valid_until": None, "cpc_code": None,
     "language": "en", "method_family": "EN15804", "pdf_url": "https://circularecology.com/wp-content/uploads/2026/01/Product-Category-Rules-v1.0.pdf",
     "detail_url": "https://circularecology.com/wp-content/uploads/2026/01/Product-Category-Rules-v1.0.pdf"},
    # ── BRE (UK) + EPD Hub PCRs — verified %PDF, HTTP 200, 2026-06-18 ──
    {"operator_id": "bre", "pcr_number": "BRE EN 15804 PCR PN514 issue 0.0 (construction p", "pcr_type": "pcr",
     "title": "BRE EN 15804 PCR PN514 issue 0.0 (construction products)", "version_label": None, "valid_until": None, "cpc_code": None,
     "language": "en", "method_family": "EN15804", "pdf_url": "https://www.greenbooklive.com/filelibrary/EN_15804/BRE_EN_15804_PCR.PN514.pdf",
     "detail_url": "https://www.greenbooklive.com/filelibrary/EN_15804/BRE_EN_15804_PCR.PN514.pdf"},
    {"operator_id": "bre", "pcr_number": "BRE Global EN 15804 EPD Scheme Document SD207 re", "pcr_type": "pcr",
     "title": "BRE Global EN 15804 EPD Scheme Document SD207 rev3", "version_label": None, "valid_until": None, "cpc_code": None,
     "language": "en", "method_family": "EN15804", "pdf_url": "https://www.greenbooklive.com/filelibrary/EN_15804/Scheme-Document-SD207.rev3.pdf",
     "detail_url": "https://www.greenbooklive.com/filelibrary/EN_15804/Scheme-Document-SD207.rev3.pdf"},
    {"operator_id": "bre", "pcr_number": "BRE EN 15804 PCR PN514 rev 0.1 (construction pro", "pcr_type": "pcr",
     "title": "BRE EN 15804 PCR PN514 rev 0.1 (construction products)", "version_label": None, "valid_until": None, "cpc_code": None,
     "language": "en", "method_family": "EN15804", "pdf_url": "https://files.bregroup.com/bre-co-uk-file-library-copy/filelibrary/Materials/BRE-EN-15804-PCR-PN514.rev-0.1.pdf",
     "detail_url": "https://files.bregroup.com/bre-co-uk-file-library-copy/filelibrary/Materials/BRE-EN-15804-PCR-PN514.rev-0.1.pdf"},
    {"operator_id": "epdhub", "pcr_number": "EPD Hub General Programme Instructions (GPI) v1.", "pcr_type": "pcr",
     "title": "EPD Hub General Programme Instructions (GPI) v1.3.1", "version_label": None, "valid_until": None, "cpc_code": None,
     "language": "en", "method_family": "EN15804", "pdf_url": "https://www.epdhub.com/_files/ugd/199f85_ad5d3cd40eec418395f710788e41b6c0.pdf",
     "detail_url": "https://www.epdhub.com/_files/ugd/199f85_ad5d3cd40eec418395f710788e41b6c0.pdf"},
    {"operator_id": "epdhub", "pcr_number": "EPD Hub Product Category Rules (PCR) v1.2.1", "pcr_type": "pcr",
     "title": "EPD Hub Product Category Rules (PCR) v1.2.1", "version_label": None, "valid_until": None, "cpc_code": None,
     "language": "en", "method_family": "EN15804", "pdf_url": "https://www.epdhub.com/_files/ugd/199f85_451db462020743c4b007603b67f3c807.pdf",
     "detail_url": "https://www.epdhub.com/_files/ugd/199f85_451db462020743c4b007603b67f3c807.pdf"},
    {"operator_id": "epdhub", "pcr_number": "EPD Hub General Programme Instructions (GPI) v1.", "pcr_type": "pcr",
     "title": "EPD Hub General Programme Instructions (GPI) v1.3", "version_label": None, "valid_until": None, "cpc_code": None,
     "language": "en", "method_family": "EN15804", "pdf_url": "https://www.epdhub.com/_files/ugd/a329b6_5bc7018018744051b402cf4b839feb7f.pdf",
     "detail_url": "https://www.epdhub.com/_files/ugd/a329b6_5bc7018018744051b402cf4b839feb7f.pdf"},
]

def harvest(max_pages=None, limit=None, operator_filter=None):
    rows = ENTRIES if not operator_filter else [e for e in ENTRIES if e["operator_id"] == operator_filter]
    out = []
    for e in rows:
        d = dict(e)
        d.setdefault("pdf_file_id", None)
        d.setdefault("all_file_ids", [])
        out.append(d)
    if limit:
        out = out[:limit]
    print(f"[manual-registry] {len(out)} curated entries")
    return out

if __name__ == "__main__":
    import json
    print(json.dumps(harvest(), indent=2, ensure_ascii=False))
